### ISSUE TITLE
error on content editing page

### ISSUE THREAD

**Issue by mnelson4** [mnelson4/printmyblog#226]
First report:
```
An error of type E_ERROR was caused in line 175 of the file /home/customer/www/nancyradford.com/public_html/wp-content/plugins/printmyblog-PRO-master/templates/project_edit_content.php. Error message: Uncaught Error: Call to a member function getDesignTemplate() on bool in /home/customer/www/nancyradford.com/public_html/wp-content/plugins/printmyblog-PRO-master/templates/project_edit_content.php:175
Stack trace:
#0 /home/customer/www/nancyradford.com/public_html/wp-content/plugins/printmyblog-PRO-master/inc/internal_functions.php(90): require()
#1 /home/customer/www/nancyradford.com/public_html/wp-content/plugins/printmyblog-PRO-master/inc/internal_functions.php(79): pmb_get_contents('/home/customer/...', Array)
#2 /home/customer/www/nancyradford.com/public_html/wp-content/plugins/printmyblog-PRO-master/src/PrintMyBlog/controllers/Admin.php(934): pmb_render_template('project_edit_co...', Array)
#3 /home/customer/www/nancyradford.com/public_html/wp-content/plugins/printmyblog-PRO-master/src/PrintMyBlog/controllers/Admin.php(839): PrintMyBlog\controllers\Admin->renderProjectTemplate('project_edit_co...', Array)
#4 /home/customer/www/nancyradford.com/public_html/wp-content/plugins/printmyblog-PRO-master/src/P
```
Plugins:
```
"Akismet Anti-Spam": "4.1.9 by Automattic ",
        "Beaver Builder Plugin (Pro Version)": "2.4.2.2 by The Beaver Builder Team ",
        "Black Studio TinyMCE Widget": "2.6.9 by Black Studio ",
        "Classic Editor": "1.6 by WordPress Contributors ",
        "Google Analytics for WordPress by MonsterInsights": "7.17.0 by MonsterInsights ",
        "Print My Blog Pro": "3.0.0 by Michael Nelson ",
        "Scriptless Social Sharing": "3.1.6 by Robin Cornett ",
        "SG Optimizer": "5.7.20 by SiteGround ",
        "UpdraftPlus - Backup/Restore": "2.16.53.1 by UpdraftPlus.Com, DavidAnderson ",
        "Wordfence Security": "7.5.2 by Wordfence ",
        "WordPress Importer": "0.7 by wordpressdotorg ",
        "Yoast SEO": "16.1.1 by Team Yoast "
```

Second report
```
An error of type E_ERROR was caused in line 175 of the file /home/carolin6/public_html/blog/wp-content/plugins/printmyblog-PRO-master/templates/project_edit_content.php. Error message: Uncaught Error: Call to a member function getDesignTemplate() on bool in /home/carolin6/public_html/blog/wp-content/plugins/printmyblog-PRO-master/templates/project_edit_content.php:175
Stack trace:
#0 /home/carolin6/public_html/blog/wp-content/plugins/printmyblog-PRO-master/inc/internal_functions.php(110): require()
#1 /home/carolin6/public_html/blog/wp-content/plugins/printmyblog-PRO-master/inc/internal_functions.php(99): pmb_get_contents('/home/carolin6/...', Array)
#2 /home/carolin6/public_html/blog/wp-content/plugins/printmyblog-PRO-master/src/PrintMyBlog/controllers/Admin.php(944): pmb_render_template('project_edit_co...', Array)
#3 /home/carolin6/public_html/blog/wp-content/plugins/printmyblog-PRO-master/src/PrintMyBlog/controllers/Admin.php(849): PrintMyBlog\controllers\Admin->renderProjectTemplate('project_edit_co...', Array)
#4 /home/carolin6/public_html/blog/wp-content/plugins/printmyblog-PRO-master/src/PrintMyBlog/controllers/Admin.php(685): PrintMyBlog\controllers\Admin->editContent()
#5 /home/ca
```
Plugins in use: 
```
 "Advanced Comment Form": "1.2.0 by Thomas Maier ",
        "Akismet Anti-Spam": "4.1.9 by Automattic ",
        "Classic Editor": "1.6 by WordPress Contributors ",
        "Easy Footnotes": "1.1.5 by Jason Yingling ",
        "Embed Any Document": "2.6.1 by Awsm Innovations ",
        "Fonts Plugin | Google Fonts Typography": "2.5.7 by Fonts Plugin ",
        "Google Site Verification plugin using Meta Tag": "1.2 by Himanshu Parashar ",
        "Google XML Sitemaps": "4.1.1 by Auctollo ",
        "iframe": "4.5 by webvitaly ",
        "iframe popup": "3.1 by Gopi Ramasamy ",
        "Jetpack by WordPress.com": "9.6.1 by Automattic ",
        "Official StatCounter Plugin": "2.0.6 by Aodhan Cullen ",
        "One-Click Child Theme": "1.6 by tychay ",
        "Print My Blog": "3.1.0 by Michael Nelson (Latest version: 3.1.1) ",
        "Public Post Preview": "2.9.3 by Dominik Schilling ",
        "ShortPixel Image Optimizer": "4.22.0 by ShortPixel ",
        "TablePress": "1.13 by Tobias Bu00e4thge ",
        "UpdraftPlus - Backup/Restore": "1.16.56 by UpdraftPlus.Com, DavidAnderson ",
        "Wordfence Security": "7.5.2 by Wordfence ",
        "WP-Optimize - Clean, Compress, Cache": "3.1.9 by David Anderson, Ruhani Rabin, Team Updraft ",
        "WP Edit": "4.0.4 by Josh Lobe ",
        "Yoast SEO": "16.2 by Team Yoast "
```
I reproduce the error by deleting the `_pmb_format` metadata, NOT by deleting designs.

**Comment by mnelson4** [comment]
Reproduced it (probably a miracle): they started a project but didn't choose the format. THen it skipped choosing and customizing either format and went straight to the content editing page and had an error.
